name: 'site'

on: push

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: å®‰è£…ä¾èµ–ğŸ› ï¸
        run: |
          npm i pnpm -g
          pnpm install --no-frozen-lockfile

      - name: ç«™ç‚¹ç”ŸæˆğŸš€
        run: pnpm site

      - name: èµ„æºåŠ è½½ğŸŒŸ
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: ç«™ç‚¹éƒ¨ç½²ğŸ’¡
        id: deployment
        uses: actions/deploy-pages@v4

permissions:
  contents: read
  pages: write
  id-token: write
