name: 'site'

on: push

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: å®‰è£…ä¾èµ–ğŸ› ï¸
        run: |
          npm i pnpm -g
          pnpm install --no-frozen-lockfile

      - name: ç«™ç‚¹ç”ŸæˆğŸš€
        run: pnpm site

      - name: ç«™ç‚¹éƒ¨ç½²ğŸŒŸ
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
